# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: godreau/test:v8
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: foo@bar.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - 8081:8081
